In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [14]:
np.arange(0,10,2) # Creates integer as default

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(shape=(10,5)) # Creates float as default

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(shape=(2,4)) # (rows,col)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.random.seed(101) # random seed number 101
arr = np.random.randint(0,100,10) # between 0 and 100 and 10 random numbers

In [19]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [20]:
arr2 = np.random.randint(0,100,10)

In [21]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40], dtype=int32)

In [22]:
arr.max()

np.int32(95)

In [24]:
arr.argmax() # index value

np.int64(0)

In [25]:
arr.min()

np.int32(9)

In [26]:
arr.argmin()

np.int64(7)

In [27]:
arr.mean()

np.float64(60.8)

In [28]:
arr.shape

(10,)

In [29]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [31]:
mat = np.arange(0,100).reshape(10,10)

In [32]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
row = 0
col = 1

In [37]:
mat[row,col]

np.int64(1)

In [38]:
mat[4,6]

np.int64(46)

In [39]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [45]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [46]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mat[0:3,0:4] = 0

In [51]:
newmat = mat.copy()

In [52]:
newmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
newmat[0:6,0:6] = 999

In [54]:
newmat

array([[999, 999, 999, 999, 999, 999,   6,   7,   8,   9],
       [999, 999, 999, 999, 999, 999,  16,  17,  18,  19],
       [999, 999, 999, 999, 999, 999,  26,  27,  28,  29],
       [999, 999, 999, 999, 999, 999,  36,  37,  38,  39],
       [999, 999, 999, 999, 999, 999,  46,  47,  48,  49],
       [999, 999, 999, 999, 999, 999,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])