In [2]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('bank_note_data.txt', delimiter = ',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:, 4]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features = data[:, 0 : 4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X = features
y = labels

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [14]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [15]:
len(X_train)

919

In [16]:
len(X)

1372

In [17]:
len(X_test)

453

In [18]:
len(y_test)

453

In [19]:
len(y_train)

919

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler = MinMaxScaler()

In [22]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
scaled_X_train = scaler.transform(X_train)

In [24]:
scaled_X_test = scaler.transform(X_test)

In [25]:
scaled_X_train.max()

1.0000000000000002

In [26]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [27]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
model = Sequential()

model.add(Dense(4, input_dim = 4, activation = 'relu'))

model.add(Dense(8, activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

In [30]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [31]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.6544 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6437 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6338 - acc: 0.5550
Epoch 4/50
 - 0s - loss: 0.6235 - acc: 0.5734
Epoch 5/50
 - 0s - loss: 0.6113 - acc: 0.6094
Epoch 6/50
 - 0s - loss: 0.5968 - acc: 0.6431
Epoch 7/50
 - 0s - loss: 0.5828 - acc: 0.6779
Epoch 8/50
 - 0s - loss: 0.5643 - acc: 0.7236
Epoch 9/50
 - 0s - loss: 0.5468 - acc: 0.7563
Epoch 10/50
 - 0s - loss: 0.5297 - acc: 0.7476
Epoch 11/50
 - 0s - loss: 0.5110 - acc: 0.7682
Epoch 12/50
 - 0s - loss: 0.4930 - acc: 0.7780
Epoch 13/50
 - 0s - loss: 0.4773 - acc: 0.7922
Epoch 14/50
 - 0s - loss: 0.4604 - acc: 0.8172
Epoch 15/50
 - 0s - loss: 0.4437 - acc: 0.8390
Epoch 16/50
 - 0s - loss: 0.4285 - acc: 0.8313
Epoch 17/50
 - 0s - loss: 0.4129 - acc: 0.8531
Epoch 18/50
 - 0s - loss: 0.3979 - acc: 0.8564
Epoch 19/50
 - 0s - loss: 0.3819 - acc: 0.8705
Epoch 20/50
 - 0s - loss: 0.3670 - acc: 0.8770
Epoch 21/50
 - 0s - loss: 0.3529 - acc: 0.8825
Epoch 22/50
 - 0s - lo

In [32]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [33]:
model.metrics_names

['loss', 'acc']

In [34]:
from sklearn.metrics import confusion_matrix, classification_report

In [35]:
predictions = model.predict_classes(scaled_X_test)

In [36]:
confusion_matrix(y_test, predictions)

array([[256,   1],
       [ 10, 186]], dtype=int64)

In [37]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98       257
        1.0       0.99      0.95      0.97       196

avg / total       0.98      0.98      0.98       453



In [38]:
model.save('mysupermodel.h5')

In [39]:
from keras.models import load_model

In [40]:
newmodel = load_model('mysupermodel.h5')

In [41]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    